### ISSUE TITLE
D3 ver. 5を使えるようにしてほしい

### ISSUE THREAD

**Issue by yasunobuigarashi** [e2d3/e2d3#53]
e2d3/src/scripts-gen/paths.js

'd3': [
    '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min',
    'd3'
  ]

でd3.jsを読み込んでいると思う

A paths.jsが読み込まれた時点でpaths.jsにライブラリーがすべて読み込まれている場合
paths.jsにd3-v5のpathを追記したら、d3-v3を上書きして過去の図が動かなくなるので
d3-v3とd3-v5を共存させるためには「一工夫＋一作業」が必要

B e2d3/contribの各図がd3を使った時点でpaths.jsの該当ライブラリーを読み込む場合
「paths.jsにd3-v5のpathを追記する」＋「contrib内でのd3-v5の呼び方を指定する」レベルの方法で解決できそう

**Comment by JunichiWatanuki** [comment]
D3jsも、最近は5.9までになってますね。
将来、6.0、7.0、、となったときのことも考えたときの設計を考える時期なのかもですね。
個人的には、グラフテンプレート（main.jsでもmanifest.ymlでもどこでもいいんで）に、対応するd3jsのバージョンを記載する方式で、テンプレ作成する方式としてほしいです。
各テンプレートが異なるバージョンのD3jsに依存していても、Excel側では、テンプレに適合したバージョンのD3jsを読みだして可視化を行わせる設計です。

理由として、これまで蓄積されているテンプレートが、D3jsのバージョン依存として作られているものがあることが挙げられることが挙げられます。
うまく改良出来たら、過去のテンプレートも将来のテンプレートも長きにわたり利用できる利点があると思います。

**Comment by hiracky16** [comment]
メモ
雰囲気で修正してみたあとに grup にあった build を走らせてみたところ以下のようなエラーが起きた。
`Error: No file for module 'FileSaver' found.`
e2d3 では bower というパッケージ管理ツール（npm みたいなもの）を使っているため `bower install` を打てば解決するかと思ったが出来ない。

bower とは
https://qiita.com/oreo3@github/items/eb790fc091aa28af8d33

**Comment by hiracky16** [comment]
`bower install` を実行すると bower.json に記述のあるパッケージが `bower-components` にインストールされる。
FileSaver もその一つで バージョンの指定はなかった。
おそらくバージョンの違いによってパッケージ内のパスが変わっているのが原因で grup のタスクが落ちていた。
bower.json 内に override があるがそこに `パッケージ名: ファイルへのパス` という形で grup タスク中で使われるパッケージが羅列されており、そのパスを修正することでエラーを回避できた。

ただ、つぎは以下のエラーが発生しておりビルドに失敗した。
`Error: No file for module 'canvg' found.`
これも同じ原因だと思ったが別のものだと思われるので引き続き調査する。

**Comment by hiracky16** [comment]
ちなみにローカルでのデバッグ方法
※ e2d3 のディレクトと contrib が同じレベルにあって e2d3 ディレクト内で行うと仮定

`bin/e2d3 ../e2d3-contrib/`

**Comment by hiracky16** [comment]
canvg のエラーの原因はこれもまたバージョンが新しくなったが原因だと思われる。
ただ、 bower 経由で古いバージョンをインストールできなくなっていたため、インストールできる一番古いバージョンで無理やり実行できるようにした。

e2d3 コマンドの実行は出来たものの FileSaver.js がサーバー上で 404 になってしまうため引き続き調査が必要。

**Comment by JunichiWatanuki** [comment]
javascriptのライブラリのバージョンが、パッケージマネージャがとってくるバージョンと異なる場合ですが、正しくはバージョン間の相性問題をひとつづつひも解いて解消するのがよいでしょう。

が、自分がpythonなどでやる(ずる)手法として、パッケージマネージャがインストール（orデプロイ）した後で、関係ファイルを実際に使いたいバージョンのファイルで上書きする案があります。
（今回それが適用できるかはわかりませんが、、）

リリース日程を優先させるのであれば、後者のずるい？手法を検討するのも一案かもしれません。
（が本質ではないので、時間稼ぎ程度に考えた方がいいです）

**Comment by JunichiWatanuki** [comment]
404エラー（ファイルがない）のであれば、現用のサーバで使っているファイルを抜いてきて、デプロイ時に当該ファイルを追加するスクリプトを追加してみて、問題切り分けしてみてはと、考えています。
※ 単にファイルがないだけなら、、とりあえずの対応に話す。しかし、この方法も本質的な解決ではないので、いずれは対処しなければならない。

**Comment by hiracky16** [comment]
FileSaver がない問題はこのコミットが原因でした。
https://github.com/e2d3/e2d3/commit/515821f6fcb896e741609136c710cbe82428116a
この修正の内容が公開されている e2d3 パッケージでは反映されていないようです。
そのため削除しても問題ないと思われるのですが、どういった要件で追加されたのかは確認したほうがよいかもです。

**Comment by JunichiWatanuki** [comment]
調査ありがとうございます。
リポジトリ内では下記のように反映はされているのに、、、
https://github.com/e2d3/e2d3/search?q=FileSaver&unscoped_q=FileSaver

下記のリポジトリが見えるのであれば、一度覗いてみてください。
https://github.com/e2d3/e2d3-server

そこでは、e2d3のリポジトリをgitサブモジュールとしてサーバ処理を担わせていたりなので。

**Comment by hiracky16** [comment]
サーバー側で扱っている e2d3 サブモジュールは 2015 年 11 月時点の情報になっています。
問題に上げたコミットは 2017 年のコミットなので反映されていないのかと思っています。

サーバーの方の e2d3 のコミットログ
https://github.com/e2d3/e2d3/commits/d8035e9b4cc0fdcde28ac6801599a2b0f2d3dcab

サーバーの方のサブモジュールを update がされていないようですね…

**Comment by hiracky16** [comment]
とりあえず manifest.yml の内容を head で読みこむようにしてみました。（動作検証はまだ）
https://github.com/e2d3/e2d3/tree/feature/read-module-from-manifest

<details><summary>manifest.yml の例</summary><div>

```yml
name: us-map
description:
tags:
  - map
homepage: https://github.com/e2d3/e2d3-contrib
bugs: https://github.com/e2d3/e2d3-contrib/issues
license: Apache-2.0
contributors:
  - Keiko Ono <keiko.ono1@gmail.com>
repository: e2d3/e2d3-contrib
capabilities:
  saveImages: false
modules:
  - https://cdnjs.cloudflare.com/ajax/libs/d3/5.15.0/d3.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/typescript/3.7.2/typescript.js
```
</div></details>
